net-misc/xmrig-mo: Algorithm switching xmrig fork
gentoo-monero/gentoo-monero pull request #2
Opened 2020-09-04 00:14 UTC by telans

For usage with the MoneroOcean mining pool
https://github.com/MoneroOcean/xmrig

2020-09-13 15:01 UTC, 00-matt commented on net-misc/xmrig-mo/xmrig-mo-6.3.3.ebuild
> +		libressl? ( dev-libs/libressl:= ) )"
```suggestion
	ssl? (
		!libressl? ( dev-libs/openssl:= )
		libressl? ( dev-libs/libressl:= )
	)"
```

2020-09-13 15:02 UTC, 00-matt commented on net-misc/xmrig-mo/xmrig-mo-6.3.3.ebuild
> +	! use donate && PATCHES+=("${FILESDIR}/${PN}-no-default-donate.patch")
```suggestion
	use donate || PATCHES+=("${FILESDIR}/${PN}-no-default-donate.patch")
```

or

```suggestion
	use donate || eapply "${FILESDIR}/${PN}-no-default-donate.patch"
```

2020-09-13 15:05 UTC, 00-matt requested changes
Great, thank you! Also please could you add a `Signed-off-by: ...` line to your commit if you can.

2020-09-15 09:08 UTC, telans commented
Cheers, updated

2020-09-15 10:01 UTC, 00-matt approved these changes

2020-09-15 10:03 UTC, closed without merging