added net-misc/feather-1.0.1 (but for real this time)
gentoo-monero/gentoo-monero pull request #32
Opened 2022-03-10 00:32 UTC by ethark

This is my first real ebuild, so you might want to take another look at this, as I don't know all the ebuild features and stuff.

I thought it would be better to use archives instead of doing `inherit git-r3` and expecting it to do the sub-modules. Firstly, because I read git-r3 is just for "live ebuilds", and secondly because it provides some reliability as distfiles are cached by gentoo infrastructure (If these ever get added to the main gentoo tree). The disadvantage is that you have to update the comits of each dependency that these feather devs re-distrubute with their package (monero), and the dependencies-of-dependencies (miniupnp, etc.) and so on.

I don't know if you want me to include the whole `repoman manifest` thing in the commit. I don't know how to do that in this repository. I just worked on this from my own `/var/db/repo/ethark`, and when I finished I copied the ebuild to ~/gentoo-monero where I made the commit.

Lastly, I'm just going to point out that it doesn't build without `media-gfx/zbar`, even if you use -DWITH_SCANNER. Look at their CMakeLists.txt, it looks like DWITH_SCANNER is just for v4l or something, dunno. Should we tell them or just patch that ourselves? Actually, screw it, we should just drop the `qrcode` useflag and make a `media-gfx/zbar` mandatory dependency.

2022-03-10 01:07 UTC, ethark commented
Also, note that the `=net-misc/feather-9999` ebuild is broken, not just because they moved their repo to https://github.com/feather-wallet/feather.git, but also because of some weird thing they are doing on the master branch: https://github.com/feather-wallet/feather/issues/5

2022-03-10 08:20 UTC, 00-matt commented
This is great! Thank you for spending some time on it, I'll try and review it properly today.

2022-03-12 08:46 UTC, 00-matt requested changes
Thanks again! Just some small changes

2022-03-12 08:46 UTC, 00-matt commented on net-misc/feather/feather-1.0.1.ebuild
> +EAPI=7
We can use EAPI-8 now.

```suggestion
EAPI=8
```

2022-03-12 08:46 UTC, 00-matt commented on net-misc/feather/feather-1.0.1.ebuild
> +	UNBOUND_DIST_COMIT="0f6c0579d66b65f86066e30e7876105ba2775ef4"
Good, Monero does the same :)

But note that the distfiles mirrors don't mirror for overlays, so if GitHub does down we are still stuck

2022-03-12 08:46 UTC, 00-matt commented on net-misc/feather/feather-1.0.1.ebuild
> +"
We should prefer the gzipped tarballs.

```suggestion
SRC_URI="https://github.com/feather-wallet/feather/archive/refs/tags/${PVR}.tar.gz -> ${PF}.tar.gz
	https://github.com/feather-wallet/monero/archive/${MONERO_DIST_COMIT}.tar.gz -> ${PF}-monero.tar.gz
	https://github.com/miniupnp/miniupnp/archive/${MINIUPNP_DIST_COMIT}.tar.gz -> ${PF}-monero-miniupnp.tar.gz
	https://github.com/tevador/RandomX/archive/${RANDOMX_DIST_COMIT}.tar.gz -> ${PF}-monero-randomx.tar.gz
	https://github.com/Tencent/rapidjson/archive/${RAPIDJSON_DIST_COMIT}.tar.gz -> ${PF}-monero-rapidjson.tar.gz
	https://github.com/monero-project/supercop/archive/${SUPERCOP_DIST_COMIT}.tar.gz -> ${PF}-monero-supercop.tar.gz
	https://github.com/trezor/trezor-common/archive/${TREZORCOMMON_DIST_COMIT}.tar.gz -> ${PF}-monero-trezorcommon.tar.gz
	https://github.com/monero-project/unbound/archive/${UNBOUND_DIST_COMIT}.tar.gz -> ${PF}-monero-unbound.tar.gz
"
```

2022-03-12 08:46 UTC, 00-matt commented on net-misc/feather/feather-1.0.1.ebuild
> +LICENSE="BSD MIT"
The trezor-common stuff is LGPL-3.0 so users need to agree to that too

```suggestion
LICENSE="BSD LGPL-3.0 MIT"
```

2022-03-12 08:46 UTC, 00-matt commented on net-misc/feather/feather-1.0.1.ebuild
> +	mv -T ${WORKDIR}/unbound-${UNBOUND_DIST_COMIT} ${WORKDIR}/${PF}/monero/external/unbound
We need to put `${WORKDIR}` in quotes just in case someone uses a path with a space :(

```suggestion
	mv -T "${WORKDIR}"/monero-${MONERO_DIST_COMIT} "${WORKDIR}"/${PF}/monero
	mv -T "${WORKDIR}"/miniupnp-${MINIUPNP_DIST_COMIT} "${WORKDIR}"/${PF}/monero/external/miniupnp
	mv -T "${WORKDIR}"/RandomX-${RANDOMX_DIST_COMIT} "${WORKDIR}"/${PF}/monero/external/randomx
	mv -T "${WORKDIR}"/rapidjson-${RAPIDJSON_DIST_COMIT} "${WORKDIR}"/${PF}/monero/external/rapidjson
	mv -T "${WORKDIR}"/supercop-${SUPERCOP_DIST_COMIT} "${WORKDIR}"/${PF}/monero/external/supercop
	mv -T "${WORKDIR}"/trezor-common-${TREZORCOMMON_DIST_COMIT} "${WORKDIR}"/${PF}/monero/external/trezor-common
	mv -T "${WORKDIR}"/unbound-${UNBOUND_DIST_COMIT} "${WORKDIR}"/${PF}/monero/external/unbound
```

2022-03-12 08:47 UTC, 00-matt commented on net-misc/feather/feather-1.0.1.ebuild
> +SRC_URI="https://github.com/feather-wallet/feather/archive/refs/tags/${PVR}.tar.gz -> ${PF}.tar.gz
Forgot to add, we should use ${PV} here. ${PVR} includes the ebuild revision (e.g. `feather-1.0.1-r1.ebuild`).

```suggestion
SRC_URI="https://github.com/feather-wallet/feather/archive/refs/tags/${PV}.tar.gz -> ${PF}.tar.gz
```

2022-03-14 02:10 UTC, ethark commented on net-misc/feather/feather-1.0.1.ebuild
> +	UNBOUND_DIST_COMIT="0f6c0579d66b65f86066e30e7876105ba2775ef4"
Yeah. Well I guess the users still have their local copy of distfiles if they need to rebuild it. that was sort of annoying when the live ebuild failed.

2022-03-14 03:02 UTC, ethark commented on net-misc/feather/feather-1.0.1.ebuild
> +SRC_URI="https://github.com/feather-wallet/feather/archive/refs/tags/${PVR}.tar.gz -> ${PF}.tar.gz
I've made the change, but why shouldn't we use $PVR? is the revision number just for the change on our side of the ebuild?

2022-03-14 03:02 UTC, ethark commented on net-misc/feather/feather-1.0.1.ebuild
> +	mv -T ${WORKDIR}/unbound-${UNBOUND_DIST_COMIT} ${WORKDIR}/${PF}/monero/external/unbound
Good catch. Fixed.

2022-03-14 03:02 UTC, ethark commented on net-misc/feather/feather-1.0.1.ebuild
> +LICENSE="BSD MIT"
Fixed.

2022-03-14 03:02 UTC, ethark commented on net-misc/feather/feather-1.0.1.ebuild
> +"
Ah, I had no idea they even offered those. Fixed.

2022-03-14 03:02 UTC, ethark commented on net-misc/feather/feather-1.0.1.ebuild
> +EAPI=7
Fixed.

2022-03-14 03:05 UTC, ethark commented
Okay, should I squash the commits

2022-03-14 08:36 UTC, 00-matt commented on net-misc/feather/feather-1.0.1.ebuild
> +SRC_URI="https://github.com/feather-wallet/feather/archive/refs/tags/${PVR}.tar.gz -> ${PF}.tar.gz
Yep. We increment the revision when changing the ebuild so that users rebuild it.

https://devmanual.gentoo.org/general-concepts/ebuild-revisions/index.html

2022-03-14 08:41 UTC, closed without merging

2022-03-14 08:41 UTC, 00-matt commented
I've squashed them both together. Thanks again!!